### ISSUE TITLE
Ne sai troppe

### ISSUE THREAD

**Issue by brosssh** [Furrrlo/declarative-ui#1]
Sono Broch in caso non si capisce :D

**Comment by Furrrlo** [comment]
Ma non abbastanza 🌵😶‍🌫️

**Comment by brosssh** [comment]
Pure github dice che sei un PRO
<img width="207" alt="image" src="https://github.com/Furrrlo/declarative-ui/assets/44944126/4666e89e-c8d5-4072-94e9-b48240dd4178">
